### ISSUE TITLE
Unhandled rejection Error: [object Object]

### ISSUE THREAD

**Issue by roelandbraam** [Fjuxx/pimatic-kodi#1]
hi, just noticed this plugin, and i tested it in my pimatic configuration.
I get however the following error:

13:45:35.199 [pimatic-kodi] Kodi connected
Unhandled rejection Error: [object Object]
    at Object.ensureErrorObject (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/util.js:226:20)
    at Promise._rejectCallback (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:427:22)
    at PromiseArray.__hardReject__.PromiseArray._reject (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise_array.js:109:19)
    at PromiseArray._promiseRejected (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise_array.js:130:10)
    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:553:26)
    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/promise.js:661:14)
    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:415:13)

any idea ?

And this error when kodi is switched off and pimatic is started:

14:01:00.819 [pimatic] A uncaught exception occured: Error: JSON parse error: Error: Unexpected end
14:01:00.819 [pimatic]>Line: 1
14:01:00.819 [pimatic]>Column: 0
14:01:00.819 [pimatic]>Char: 
14:01:00.819 [pimatic]>    at Object.onerror (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/lib/TCPConnection.js:186:17)
14:01:00.819 [pimatic]>    at emit (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:285:37)
14:01:00.819 [pimatic]>    at error (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:320:5)
14:01:00.819 [pimatic]>    at end (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:326:7)
14:01:00.819 [pimatic]>    at Object.write (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:341:32)
14:01:00.819 [pimatic]>    at Object.CParser.close (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/node_modules/clarinet/clarinet.js:148:42)
14:01:00.819 [pimatic]>    at Connection.onClose (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/lib/TCPConnection.js:162:26)
14:01:00.819 [pimatic]>    at Socket.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-kodi/node_modules/xbmc/lib/TCPConnection.js:4:59)
14:01:00.819 [pimatic]>    at Socket.EventEmitter.emit (events.js:95:17)
14:01:00.819 [pimatic]>    at TCP.close (net.js:466:12)
14:01:00.819 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!

**Comment by Fjuxx** [comment]
Hi,

i also came across this error.

Seems i forgot to test if there was nothing playing.
I depend a lot on node-xbmc, But it seems full of bugs.

i think i solved a few now and added some new functionality.

Do an update and try again. it works fine here now.

Please note i did not test yet what happens if Kodi/XBMC is offline.

**Comment by roelandbraam** [comment]
Yep , now it works ! Nice work 
I will test some more with it, also when kodi is offline.
